# Generated by Django 4.0.2 on 2022-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='one_to_fifteen_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
